version: '3'
services: 
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASS=$MYSQLDB_PASS
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  api:
    depends_on:
      - mysqldb
    build: ../.
    restart: on-failure:3
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    stdin_open: true
    tty: true
  app:
    depends_on:
      - api
    build: ../../web-customer-tracker/.
    restart: on-failure:3
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT_APP:$SPRING_DOCKER_PORT_APP
    stdin_open: true
    tty: true
volumes:
  db:
